language: java
sudo: false

jdk:
  - oraclejdk8

install:
- mvn clean install

script:
- mvn clean verify
  
after_success:
- mvn clean test jacoco:report coveralls:report


cache:
  directories:
    # local Maven repository
    - '$HOME/.m2/repository'

notifications:
  email:
    on_success: never
    on_failure: always

